"""Projection schema constants."""

from catalyst.projection.schemas.schema_version import (
    AUDIT_SCHEMA_VERSION,
    BOUNDARY_INSPECTION_SCHEMA_VERSION,
    CANDIDATE_EVALUATION_SCHEMA_VERSION,
    CONTEXT_RECOVERY_BENCHMARK_SCHEMA_VERSION,
    PARENT_CHILD_SCHEMA_VERSION,
    RETRIEVAL_SCHEMA_VERSION,
    RETRIEVAL_SANITY_SCHEMA_VERSION,
    SENTENCE_WINDOW_SCHEMA_VERSION,
)

__all__ = [
    "AUDIT_SCHEMA_VERSION",
    "BOUNDARY_INSPECTION_SCHEMA_VERSION",
    "CANDIDATE_EVALUATION_SCHEMA_VERSION",
    "CONTEXT_RECOVERY_BENCHMARK_SCHEMA_VERSION",
    "PARENT_CHILD_SCHEMA_VERSION",
    "RETRIEVAL_SCHEMA_VERSION",
    "RETRIEVAL_SANITY_SCHEMA_VERSION",
    "SENTENCE_WINDOW_SCHEMA_VERSION",
]
